import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const production = process.argv[2] === "production";

// Two independent bundles, mirroring the two-process architecture (CLAUDE.md
// rule 7): the extension host (Node, CommonJS, "vscode" external) and the
// webview (browser, IIFE, no Node/vscode access at all — messages only).
const extensionContext = await esbuild.context({
	banner: {
		js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. If you want to view the source, visit the github repository of this extension */",
	},
	entryPoints: ["src/extension.ts"],
	bundle: true,
	external: ["vscode", "electron", ...builtins],
	format: "cjs",
	platform: "node",
	target: "es2020",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: "dist/extension.js",
	minify: production,
});

const webviewContext = await esbuild.context({
	banner: {
		js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. If you want to view the source, visit the github repository of this extension */",
	},
	entryPoints: ["webview/main.ts"],
	bundle: true,
	// The webview is a plain browser context: no "vscode" or Node built-ins
	// are reachable from it (CLAUDE.md rule 7 / plan §4) — host<->webview
	// communication is exclusively postMessage, wired up in a later
	// milestone. Nothing needs to be marked external here.
	format: "iife",
	platform: "browser",
	target: "es2020",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: "media/webview.js",
	minify: production,
});

if (production) {
	await Promise.all([extensionContext.rebuild(), webviewContext.rebuild()]);
	process.exit(0);
} else {
	await Promise.all([extensionContext.watch(), webviewContext.watch()]);
}
